add event-tracker parser for webmontag.de
webmontag/webmontag-koeln.de-reloaded pull request #1
Opened 2016-10-18 16:21 UTC by amed9

2016-10-20 15:56 UTC, jhilden requested changes

2016-10-20 15:56 UTC, jhilden commented on data/webmondays_v.yaml
> +- name: 52. Webmontag
this should be deleted.

2016-10-20 15:56 UTC, jhilden commented on lib/event_tracker.rb
> +divider
naming suggstion `print_divider`.  this would be a little bit clearer on what it does

2016-10-20 15:56 UTC, jhilden commented on lib/event_tracker.rb
> +archive = webmontag_wiki_site.css('.archive li div')
maybe call it `archive_index`?

2016-10-20 15:56 UTC, jhilden commented on lib/event_tracker.rb
> +archive_clean = Array.new
why are you using a new array here?  have you considered just modifying the original archive array?

2016-10-20 15:56 UTC, jhilden commented on lib/event_tracker.rb
> +archive_blocked = Array.new
as far as I understand this, the `archive_blocked` varialbe just holds a list of events, right?  so maybe just calling it `events` would be more appropiate (and calling the the class `Event`)?

2016-10-20 15:56 UTC, jhilden commented on lib/event_tracker.rb
> +puts "Creating Yaml file /data/webmondays.yaml ".green
file extension shoud be `.yml` instead of `.yaml`

2016-10-20 15:56 UTC, jhilden commented on lib/event_tracker.rb
> +yaml_blob = archive_blocked.reverse + data
what is this doing?  can't we simply dump/overwrite the .yml file with our parsed events?

2016-10-20 15:56 UTC, jhilden commented on lib/event_tracker.rb
> +require './event_tracker_haystack.rb'
I don't understand the filename.  haystack??

2016-10-20 15:56 UTC, jhilden commented on lib/event_tracker_haystack.rb
> +class EventBlock
the `Event` class should be in its own file which is called like the class

2016-10-20 15:56 UTC, jhilden commented on lib/event_tracker_haystack.rb
> +def divider
this should go into some "utils" file

2016-10-20 15:56 UTC, jhilden commented on lib/event_tracker_haystack.rb
> +  def initialize (event_element, index)
I would pass in the `href` and the `name` individually into the constructor.  the Event does not need to coupled to the notion of an element that holds the information.

2016-10-20 15:56 UTC, jhilden commented on lib/event_tracker_haystack.rb
> +  def initialize (event_element, index)
or actually I guess the `name` should be passed in as `date`

2016-10-20 16:25 UTC, jhilden commented on lib/event_tracker.rb
> +archive = webmontag_wiki_site.css('.archive li div')
or maybe just "event_index"?

2016-10-21 00:52 UTC, amed9 commented on lib/event_tracker.rb
> +yaml_blob = archive_blocked.reverse + data
This was from early structure. We have changed the flow of the script.

2016-10-21 01:01 UTC, amed9 commented on lib/event_tracker_haystack.rb
> +  def initialize (event_element, index)
I don't fully trust that name could be the link structure 100%

2016-10-21 01:07 UTC, amed9 commented on lib/event_tracker_haystack.rb
> +  def initialize (event_element, index)
I think it is okay to keep the (event_element, index) What is the point to make it individually passed?

2016-10-21 01:18 UTC, amed commented on lib/event_tracker.rb
> +archive_clean = Array.new
"events_index" is not an array, it is Nokogiri::XML::NodeSet.
There is need to create this.

2016-10-21 01:18 UTC, amed9 commented on lib/event_tracker.rb
> +archive_clean = Array.new
events_index_array

2016-10-24 13:31 UTC, jhilden approved these changes

2016-10-24 13:38 UTC, merged