3 template behaviour webmondays.yml
webmontag/webmontag-koeln.de-reloaded pull request #12
Opened 2016-10-25 16:05 UTC by amed9

2016-10-25 19:51 UTC, jhilden requested changes
I want to see at least one test that renders the homepage (and maybe switches the languuage).  Capybara seems like the right tool for this.

2016-10-25 19:51 UTC, jhilden commented on config.rb
> +  def d(string)
`d` is not a good human-understandable name in my opinion

2016-10-25 19:51 UTC, jhilden commented on lib/events-scraper.rb
> +  # break if index == 5
???

2016-10-25 19:51 UTC, jhilden commented on lib/events-scraper.rb
> +  # break if index == 5
also the seems like it should not be part of this PR

2016-10-25 19:51 UTC, jhilden commented on source/index.html.slim
> +- next_event = upcoming_events.pop
very nice :+1:

2016-10-25 19:51 UTC, jhilden commented on source/index.html.slim
> +	      	=next_event.date
localization is still missing here, correct?

2016-10-25 19:55 UTC, jhilden commented
the automatic deployments with netlify are working now :+1:   you can see a preview build of this PR here https://deploy-preview-12--webmontag.netlify.com/

2016-10-26 07:24 UTC, amed9 commented on config.rb
> +  def d(string)
Is it okay to name it date? we use it very often, to name it d depends on the people that they will develop it.
Vorschlaege?

2016-10-26 07:27 UTC, amed9 commented on source/index.html.slim
> +	      	=next_event.date
It is better to have the localization in other ticket. maybe I have to write too much before turn it to Deutsch.

2016-10-26 07:49 UTC, jhilden commented on source/index.html.slim
> +	      	=next_event.date
that's a good idea :+1: 

in that case it would be good if you would create that ticket and mentioned it in this PR

2016-10-26 07:51 UTC, jhilden commented on config.rb
> +  def d(string)
>  it depends on the people that they will develop it

yes.  and the people developing this site could be changing a lot.  so we should choose a name that makes send to the next junior developer.

the name should describe what it is doing or what it is used for, so I would suggest something like `parse_date` maybe?

2016-10-26 14:30 UTC, jhilden commented
Deploy preview ready!

Built with commit 29814ed7fd234837866cdefdc726ec73ca2212fb

https://deploy-preview-12--webmontag.netlify.com

2016-10-26 14:32 UTC, amed9 commented
We should merge it.

2016-10-26 14:33 UTC, merged